name: Angular-StateAdapt

env:
  node-version: 20.12.1
  #NODE_OPTIONS: --max_old_space=6144 is not allowed in NODE_OPTIONS (on GitHub)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
  workflow_dispatch:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      #- name: Install PNPM, faster
      #  run: npm install --global pnpm

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build
  # TODO:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Node.js ${{ env.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ env.node-version }}

  #     #- name: Install PNPM, faster
  #     #  run: npm install --global pnpm

  #     - name: Install Dependencies
  #       run: npm ci

  #     - name: Test projects
  #       run: npm run test
